import { Deck } from './deck.ts'

export const playingCards: Deck = { //TODO double check
  name: 'Playing Cards',
  icon: '',
  back_url: '/playing-cards/card_back.png',
  cards: [
    {
      name: '',
      url: '/playing-cards/2_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/2_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/2_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/2_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/3_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/3_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/3_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/3_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/4_of_clubs.png',
      desc: '',
      effect: '',
    },

    {
      name: '',
      url: '/playing-cards/4_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/4_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/4_of_spades.png',
      desc: '',
      effect: '',
    },

    {
      name: '',
      url: '/playing-cards/5_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/5_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/5_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/5_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/6_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/6_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/6_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/6_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/7_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/7_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/7_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/7_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/8_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/8_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/8_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/8_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/9_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/9_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/9_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/9_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/10_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/10_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/10_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/10_of_spades.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/ace_of_clubs.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/ace_of_diamonds.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/ace_of_hearts.png',
      desc: '',
      effect: '',
    },
    {
      name: '',
      url: '/playing-cards/ace_of_spades.png',
      desc: '',
      effect: '',
    },
    {
        name: '',
        url: '/playing-cards/jack_of_clubs.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/jack_of_diamonds.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/jack_of_hearts.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/jack_of_spades.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/king_of_clubs.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/king_of_diamonds.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/king_of_hearts.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/king_of_spades.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/queen_of_clubs.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/queen_of_diamonds.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/queen_of_hearts.png',
        desc: '',
        effect: '',
      },
      {
        name: '',
        url: '/playing-cards/queen_of_spades.png',
        desc: '',
        effect: '',
      },
    {
      name: '',
      url: '/playing-cards/black_joker.png',
      desc: '',
      effect: '',
    },

    {
      name: '',
      url: '/playing-cards/red_joker.png',
      desc: '',
      effect: '',
    },
  ],
}
